---
title: "Anexo A"
author: "Augusto Cesar Ribeiro Nunes - 13/0103004"
date: "June 1, 2015"
output: pdf_document
---

```{r preparacao, echo=F, message=F, warning=F}
require(readr)
require(NSM3)
require(BSDA)
require(pander)
dados1 <- read_csv("Questao 1.csv")
dados2 <- read_delim("Questao 2.csv", delim=";")
for(i in 1:length(dados2[,1])){
if(dados2$SEXO[i] == "1"){
  dados2$SEXO[i] = "Masculino"
}
if(dados2$SEXO[i] == "2"){
  dados2$SEXO[i] = "Feminino"
}}
dados2$DIAST <- as.integer(difftime(strptime(dados2$TN,format="%d/%m/%Y"), strptime(dados2$T0, format="%d/%m/%Y")))
dados2$DELTA <- dados2$CD4TN - dados2$CD4T0
```
```{r var_Tamanho, echo=FALSE}
#Tamanho do lote
for(i in 1:length(dados1[,1])){
  if(dados1$Grupo[i] == "comparacao" & dados1$AREA[i] < median(as.numeric(dados1$AREA[which(dados1$Grupo == "comparacao")]))){
    dados1$Tamanho[i] = "pequeno"
  }
  if(dados1$Grupo[i]== "comparacao" & dados1$AREA[i] >= median(as.numeric(dados1$AREA[which(dados1$Grupo == "comparacao")]))){
    dados1$Tamanho[i] = "grande"
  }
  if(dados1$Grupo[i] == "projeto" & dados1$AREA[i] < median(as.numeric(dados1$AREA[which(dados1$Grupo == "projeto")]))){
    dados1$Tamanho[i] = "pequeno"
  }
  if(dados1$Grupo[i]== "projeto" & dados1$AREA[i] >= median(as.numeric(dados1$AREA[which(dados1$Grupo == "projeto")]))){
    dados1$Tamanho[i] = "grande"
  }
}
```
```{r valoradd}
for(i in 1:length(dados1[,1])){
  dados1$Val_Ad[i] = dados1$VV2007[i] - dados1$VV2001[i]
}
```


#Gráficos de descrição exploratória - Questão 1
```{r exploratoria questão 1, echo=FALSE}
par(mfrow=c(1,2), cex.main=0.6)
plot(density(dados1$Val_Ad[which(dados1$Grupo == "comparacao")]), 
     main="Densidade do Valor Adicionado na área de comparação")
plot(density(dados1$Val_Ad[which(dados1$Grupo == "projeto")]), 
     main="Densidade do Valor Adicionado na área de projeto")

```



#Tabela 1 completa - Questão 1
```{r tabela1}
categorias <- c("Estrutura de Madeira, sem banheiro/banheiro externo, sem esgotamento sanitário, pequenos",
                "Estrutura de Madeira, sem banheiro/banheiro externo, com esgotamento sanitário, pequenos",
                "Estrutura de Madeira, sem banheiro/banheiro externo, sem esgotamento sanitário, grandes",
                "Estrutura de Madeira, sem banheiro/banheiro externo, com esgotamento sanitário, grandes",
                "Estrutura de Madeira, banheiro interno, sem esgotamento sanitário, pequenos",
                "Estrutura de Madeira, banheiro interno, com esgotamento sanitário, pequenos",
                "Estrutura de Madeira, banheiro interno, sem esgotamento sanitário, grandes",
                "Estrutura de Madeira, banheiro interno, com esgotamento sanitário, grandes",
                "Estrutura de Concreto, sem banheiro/banheiro externo, sem esgotamento sanitário, pequenos",
                "Estrutura de Concreto, sem banheiro/banheiro externo, com esgotamento sanitário, pequenos",
                "Estrutura de Concreto, sem banheiro/banheiro externo, sem esgotamento sanitário, grandes",
                "Estrutura de Concreto, sem banheiro/banheiro externo, com esgotamento sanitário, grandes",
                "Estrutura de Concreto, banheiro interno, sem esgotamento sanitário, pequenos",
                "Estrutura de Concreto, banheiro interno, com esgotamento sanitário, pequenos",
                "Estrutura de Concreto, banheiro interno, sem esgotamento sanitário, grandes",
                "Estrutura de Concreto, banheiro interno, com esgotamento sanitário, grandes")


pvalores <- c((wilcox.test(dados1$Val_Ad[which(dados1$Grupo == "comparacao" & 
                                                     dados1$ESTRUTURA == "Madeira" &
                                                     dados1$Banheiros == "Externa" |
                                                     dados1$Banheiros == "Sem" &
                                                     dados1$Esgoto == "Não" & 
                                                     dados1$Tamanho == "pequeno")], 
                               dados1$Val_Ad[which(dados1$Grupo == "projeto" & 
                                                     dados1$ESTRUTURA == "Madeira" & 
                                                     dados1$Banheiros == "Externa" | 
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Não" &
                                                     dados1$Tamanho == "pequeno")], alternative="greater")$p.value),
            (wilcox.test(dados1$Val_Ad[which(dados1$Grupo == "comparacao" & 
                                                     dados1$ESTRUTURA == "Madeira" &
                                                     dados1$Banheiros == "Externa" |
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Sim" & 
                                                     dados1$Tamanho == "pequeno")], 
                               dados1$Val_Ad[which(dados1$Grupo == "projeto" & 
                                                     dados1$ESTRUTURA == "Madeira" & 
                                                     dados1$Banheiros == "Externa" | 
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Sim" &
                                                     dados1$Tamanho == "pequeno")], alternative="greater")$p.value),
            (wilcox.test(dados1$Val_Ad[which(dados1$Grupo == "comparacao" & 
                                                     dados1$ESTRUTURA == "Madeira" &
                                                     dados1$Banheiros == "Externa" |
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Não" & 
                                                     dados1$Tamanho == "grande")], 
                               dados1$Val_Ad[which(dados1$Grupo == "projeto" & 
                                                     dados1$ESTRUTURA == "Madeira" & 
                                                     dados1$Banheiros == "Externa" | 
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Não" &
                                                     dados1$Tamanho == "grande")], alternative="greater")$p.value),
            (wilcox.test(dados1$Val_Ad[which(dados1$Grupo == "comparacao" & 
                                                     dados1$ESTRUTURA == "Madeira" &
                                                     dados1$Banheiros == "Externa" |
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Sim" & 
                                                     dados1$Tamanho == "grande")], 
                               dados1$Val_Ad[which(dados1$Grupo == "projeto" & 
                                                     dados1$ESTRUTURA == "Madeira" & 
                                                     dados1$Banheiros == "Externa" | 
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Sim" &
                                                     dados1$Tamanho == "grande")], alternative="greater")$p.value),
          (wilcox.test(dados1$Val_Ad[which(dados1$Grupo == "comparacao" & 
                                                     dados1$ESTRUTURA == "Madeira" &
                                                     dados1$Banheiros == "Interna" &
                                                     dados1$Esgoto == "Não" & 
                                                     dados1$Tamanho == "pequeno")], 
                               dados1$Val_Ad[which(dados1$Grupo == "projeto" & 
                                                     dados1$ESTRUTURA == "Madeira" & 
                                                     dados1$Banheiros == "Interna" & 
                                                     dados1$Esgoto == "Não" &
                                                     dados1$Tamanho == "pequeno")], alternative="greater")$p.value),
  "Não há observações suficientes no grupo de Projeto para aplicar o teste",
          "Não há observações suficientes no grupo de Projeto para aplicar o teste",
          "Não há observações suficientes no grupo de Comparação para aplicar o teste",

(wilcox.test(dados1$Val_Ad[which(dados1$Grupo == "comparacao" & 
                                                     dados1$ESTRUTURA == "Concreto" &
                                                     dados1$Banheiros == "Externa" |
                                                     dados1$Banheiros == "Sem" &
                                                     dados1$Esgoto == "Não" & 
                                                     dados1$Tamanho == "pequeno")], 
                               dados1$Val_Ad[which(dados1$Grupo == "projeto" & 
                                                     dados1$ESTRUTURA == "Concreto" & 
                                                     dados1$Banheiros == "Externa" | 
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Não" &
                                                     dados1$Tamanho == "pequeno")], alternative="greater")$p.value),
            (wilcox.test(dados1$Val_Ad[which(dados1$Grupo == "comparacao" & 
                                                     dados1$ESTRUTURA == "Concreto" &
                                                     dados1$Banheiros == "Externa" |
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Sim" & 
                                                     dados1$Tamanho == "pequeno")], 
                               dados1$Val_Ad[which(dados1$Grupo == "projeto" & 
                                                     dados1$ESTRUTURA == "Concreto" & 
                                                     dados1$Banheiros == "Externa" | 
                                                     dados1$Banheiros == "Sem" & 
                                                     dados1$Esgoto == "Sim" &
                                                     dados1$Tamanho == "pequeno")], alternative="greater")$p.value),
            "Não há observações suficientes no grupo de Projeto para aplicar o teste",
            "Não há observações suficientes no grupo de Projeto para aplicar o teste",
          "Não há observações suficientes no grupo de Projeto para aplicar o teste",
          "Não há observações suficientes no grupo de Projeto para aplicar o teste",
          "Não há observações suficientes no grupo de Projeto para aplicar o teste",
          "Não há observações suficientes no grupo de Projeto para aplicar o teste")


conclusoes <- c("Rejeita-se a hipótese nula",
                "Rejeita-se a hipótese nula",
                "Rejeita-se a hipótese nula",
                "Rejeita-se a hipótese nula",
                "Rejeita-se a hipótese nula",
                "Inconclusivo, o teste é não aplicável",
                "Inconclusivo, o teste é não aplicável",
                "Inconclusivo, o teste é não aplicável",
                "No limiar da significância estatística, não podemos rejeitar a hipótese nula",
                "No limiar da significância estatística, não podemos rejeitar a hipótese nula",
                "Inconclusivo, o teste é não aplicável",
                "Inconclusivo, o teste é não aplicável",
                "Inconclusivo, o teste é não aplicável",
                "Inconclusivo, o teste é não aplicável",
                "Inconclusivo, o teste é não aplicável",
                "Inconclusivo, o teste é não aplicável")



tab1 <- data.frame(categorias, pvalores, conclusoes)
pander(tab1, style="rmarkdown")
```


#Gráficos - Questão 2
```{r explq2}
par(mfrow=c(2,1))
plot(dados2$DIAST[which(dados2$grupo == "1")], dados2$DELTA[which(dados2$grupo == "1")], 
     xlab = "Duração (dias) do tratamento", ylab="Diferença na contagem CD4",
     main = "Distribuição da diferença na contagem de diferença de linfócitos CD4\n 
     em relação à duração do tratamento - Grupo Controle")
abline(lm(dados2$DELTA[which(dados2$grupo == "1")]~dados2$DIAST[which(dados2$grupo == "1")]))
lm(dados2$DELTA[which(dados2$grupo == "1")]~dados2$DIAST[which(dados2$grupo == "1")])
plot(dados2$DIAST[which(dados2$grupo == "0")], dados2$DELTA[which(dados2$grupo == "0")], 
     xlab = "Duração (dias) do tratamento", ylab="Diferença na contagem CD4",
     main = "Distribuição da diferença na contagem de diferença de linfócitos CD4\n 
     em relação à duração do tratamento - Grupo Caso")
abline(lm(dados2$DELTA[which(dados2$grupo == "0")]~dados2$DIAST[which(dados2$grupo == "0")]))
lm(dados2$DELTA[which(dados2$grupo == "0")]~dados2$DIAST[which(dados2$grupo == "0")])

plot(dados2$IDADE[which(dados2$grupo == "1")], dados2$DELTA[which(dados2$grupo == "1")], 
     xlab = "Idade (anos completos)", ylab="Diferença na contagem CD4",
     main = "Distribuição da diferença na contagem de diferença de linfócitos CD4\n 
     em relação à idade do paciente - Grupo Controle")
abline(lm(dados2$DELTA[which(dados2$grupo == "1")]~dados2$IDADE[which(dados2$grupo == "1")]))
lm(dados2$DELTA[which(dados2$grupo == "1")]~dados2$IDADE[which(dados2$grupo == "1")])
plot(dados2$IDADE[which(dados2$grupo == "0")], dados2$DELTA[which(dados2$grupo == "0")], 
     xlab = "Idade (anos completos)", ylab="Diferença na contagem CD4",
     main = "Distribuição da diferença na contagem de diferença de linfócitos CD4\n 
     em relação à idade do paciente - Grupo Caso")
abline(lm(dados2$DELTA[which(dados2$grupo == "0")]~dados2$IDADE[which(dados2$grupo == "0")]))
lm(dados2$DELTA[which(dados2$grupo == "0")]~dados2$IDADE[which(dados2$grupo == "0")])

lm(dados2$DELTA[which(dados2$grupo == 0)]~dados2$SEXO[which(dados2$grupo == 0)])
lm(dados2$DELTA[which(dados2$grupo == 1)]~dados2$SEXO[which(dados2$grupo == 1)])
```



```{r testes de hip q2}
#p-valor do Teste de Ansari para a Distribuição da contagem nos grupos controle e caso
#variåvel controlada: idade mediana
#Hipótese alternativa: Distribuições diferentes em escala e/ou locação
1 - pnorm(MillerJack(dados2$DELTA[which(dados2$grupo == "1" & dados2$IDADE < 41)],dados2$DELTA[which(dados2$grupo == "0" & dados2$IDADE< 38)])) 

1 - pnorm(MillerJack(dados2$DELTA[which(dados2$grupo == "1" & dados2$IDADE >= 41)],dados2$DELTA[which(dados2$grupo == "0" & dados2$IDADE >= 38)])) 



```